channels:
  - conda-forge

dependencies:
  - jupyterlab
  - ipympl
  - jupyter_bokeh

  - python ~=3.12
  - emsarray ~=0.7
  - numpy ~=2.0
  - xarray ~=2024.06
  - bokeh ~=3.5
  - netCDF4 ~=1.7
  - ffmpeg
